Side Menu && Liferay Content && Style Book
jairmedeiros/liferay-portal pull request #2
Opened 2021-12-01 14:11 UTC by Lucas2691

2021-12-01 19:44 UTC, jairmedeiros requested changes
LGTM, but see my suggestions :)

2021-12-01 19:44 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/src/main/zippableResources/fragments/customer/fragments/liferay-contact/index.html
> +	<h5 class="text-neutral-10 h5 mb-4 rounded-sm skeleton" id="customer-portal-liferay-contact-title">
double h5 (class and tag), need to choose between it.

2021-12-01 19:44 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/src/main/zippableResources/fragments/customer/fragments/side-menu/index.css
>  	display: flex !important;
This important is necessary?

2021-12-01 19:44 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/src/main/zippableResources/fragments/customer/fragments/side-menu/index.css
>  	color: var(--color-action-primary-hover) !important;
This important is necessary?

2021-12-01 19:44 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/src/main/zippableResources/fragments/customer/fragments/side-menu/index.css
> +	border-radius: var(--border-radius);
Maybe there are a better token, like --border-radius-lg, xl, sm.

2021-12-01 19:44 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/src/main/zippableResources/fragments/customer/fragments/side-menu/index.css
>  	border-radius: var(--border-radius) !important;
Maybe there are a better token, like --border-radius-lg, xl, sm. Check this important

2021-12-01 19:44 UTC, jairmedeiros commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/src/main/zippableResources/fragments/customer/fragments/side-menu/index.css
> +	color: var(--color-action-primary-hover) !important;
Check this important.

2021-12-01 20:00 UTC, Lucas2691 commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/src/main/zippableResources/fragments/customer/fragments/liferay-contact/index.html
> +	<h5 class="text-neutral-10 h5 mb-4 rounded-sm skeleton" id="customer-portal-liferay-contact-title">
Done!

2021-12-02 01:25 UTC, Lucas2691 commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/src/main/zippableResources/fragments/customer/fragments/side-menu/index.css
>  	color: var(--color-action-primary-hover) !important;
Yes, this _!important_ is necessary to apply correct color.

2021-12-02 01:34 UTC, Lucas2691 commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/src/main/zippableResources/fragments/customer/fragments/side-menu/index.css
> +	border-radius: var(--border-radius);
The correctly is _--border-radius_ , because it has 0.5rem (8px) like a mockup.

2021-12-02 01:38 UTC, Lucas2691 commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/src/main/zippableResources/fragments/customer/fragments/side-menu/index.css
>  	border-radius: var(--border-radius) !important;
Done. The border radius isn't necessary because is the same like a _btn-menu_ tag.

2021-12-02 01:40 UTC, Lucas2691 commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/src/main/zippableResources/fragments/customer/fragments/side-menu/index.css
>  	display: flex !important;
Done.

2021-12-02 01:53 UTC, Lucas2691 commented on modules/dxp/apps/osb/osb-site-initializer/osb-site-initializer-customer-portal/src/main/zippableResources/fragments/customer/fragments/side-menu/index.css
> +	color: var(--color-action-primary-hover) !important;
Done. Check all _!important_

2021-12-02 18:42 UTC, merged